import {Inter} from "next/font/google";
import "./globals.css";
import Layout from '../component/layout'

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App111",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="zh-cn">
        <body className={inter.className}>
            <Layout>{children}</Layout>
        </body>
        </html>
    );
}
